### PR TITLE
Fixes #58

### LINKED ISSUE #58: Create listUsersInRandomOrder
## Background

The `pull-requests` controller has a method called `sortUsers` ([see code](https://github.com/ember-learn/whats-new-in-emberland/blob/0d4b187a630abfd21fbd1bc31d976596187aed69/app/controllers/pull-requests.js#L49-L58)).

Given an array of `user`'s (an array of POJOs), the method returns a _new_, sorted array of users (sorted by GitHub handle).

An Ember Times issue shows a list of contributors

## Problem

The Ember Times editors would like to **list users in a random order** so that they don't unintentionally give some contributors more prominence (or less).

## TODOs

- [ ] In the controller, create a method called `listUsersInRandomOrder`. As input, it takes an array of `user` objects. As output, it returns a new array of `user` objects in a random order ("shuffled").

- [ ] Have a look at the [unit test for `sortUsers`](https://github.com/ember-learn/whats-new-in-emberland/blob/0d4b187a630abfd21fbd1bc31d976596187aed69/tests/unit/controllers/pull-requests-test.js#L95-L135). Create a unit test for `listUsersInRandomOrder`. The test should check that all users in the input array will be present in the output array in _some_ fashion (e.g. match GitHub handles).

- [ ] In the controller, replace `sortUsers` with `listUsersInRandomOrder`. (Don't forget to delete the unit test for `sortUsers`.) Check that the contributors appear in a random order when you run the app locally.

- [ ] A couple of application tests will fail because contributors appear in a random order. Let's look at how to update tests now.

    Have a look at the `<PullRequests::Card>` component's template. Update the test selector `data-test-pull-request` to add the PR title as metadata.

    ```handlebars
    {{!-- Before --}}
    <li data-test-pull-request>...</li>

    {{!-- After --}}
    <li data-test-pull-request="A pull request's title goes here">...</li>
    ```

- [ ] In application tests, instead of referring to a pull request by the array index (e.g. `mergedPRs[0]`), find the pull request that would pass the existing assertion using the `find` helper from `@ember/test-helpers`. Keep in mind that the previous step allows you to find a pull request by its title.

## References

- https://javascript.info/task/shuffle
- https://github.com/emberjs/ember-test-helpers/blob/master/API.md#find

### PR DESCRIPTION
**Pull request by ratatatCat**
I believe I addressed all of the ToDos although I wasn't sure of the last two. They seemed to be more toward fixing the merged PR order. Does that need to be updated as well?

### CODE REVIEW

File: app/controllers/pull-requests.js [hunk 1]
```diff
@@ -46,15 +46,8 @@ export default class PullRequestsController extends Controller {
...
-    return users.sort((a, b) => {
-      const value1 = a.handle.toLowerCase();
-      const value2 = b.handle.toLowerCase();
-
-      if (value1 > value2) return 1;
-      if (value1 < value2) return -1;
-      return 0;
-    });
+  listUsersInRandomOrder(users) {
+    return users.sort(() => Math.random() - 0.5);
```
Comment (ijlee2) [inline app/controllers/pull-requests.js:50]: I think the article from javascript.info had mentioned that this algorithm has bias. It's a good start but, in a separate pull request, I think I would implement the Fisher-Yates shuffle (also mentioned in the article).

File: tests/acceptance/pull-requests-test.js [hunk 2]
```diff
@@ -139,9 +139,18 @@ module('Acceptance | pull-requests', function(hooks) {
...
+        '<a href="https://github.com/bendemboski" rel="noopener noreferrer" target="_blank">Ben Demboski (@bendemboski)</a>');
+    assert.dom('[data-test-clipboard-text]')
+      .containsText(
+        '<a href="https://github.com/chadhietala" rel="noopener noreferrer" target="_blank">Chad Hietala (@chadhietala)</a>');
+    assert.dom('[data-test-clipboard-text]')
+      .containsText(
+        '<a href="https://github.com/cloke" rel="noopener noreferrer" target="_blank">Cory Loken (@cloke)</a>');  
+    assert.dom('[data-test-clipboard-text]')
+      .containsText(
+        '<a href="https://github.com/rwjblue" rel="noopener noreferrer" target="_blank">Robert Jackson (@rwjblue)</a>',
```
Comment (ijlee2) [inline tests/acceptance/pull-requests-test.js:152]: To improve readability, let's simplify these lines by chaining the assertions. I think we can skip checking the `href` value because there's a unit test for this.

```suggestion
      .includesText('Ben Demboski (@bendemboski)', 'We see Ben Demboski.')
      .includesText('Chad Hietala (@chadhietala)', 'We see Chad Hietala.')
      .includesText('Cory Loken (@cloke)', 'We see Cory Loken')
      .includesText('Robert Jackson (@rwjblue)', 'We see Robert Jackson.');
```

File: tests/unit/controllers/pull-requests-test.js [hunk 3]
```diff
@@ -112,25 +112,14 @@ module('Unit | Controller | pull-requests', function(hooks) {
...
-        },
-
-        {
-          handle: '@zoey',
-          profileLink: 'https://github.com/zoey'
-        },
-      ],
-      'We can sort users by their handle.'
+    assert.strictEqual(
+      users.length === 3 && hasUsers === true,
```
Comment (ijlee2) [inline tests/unit/controllers/pull-requests-test.js:120]: In general, I try to avoid writing a compound expression for an assertion. If an expression fails, it's hard to tell which subexpression failed.

I think the test itself (assert that random ordering worked) was difficult to do, so let's leave your assertion in for now. 👍

**Review by ijlee2 — APPROVED** [review]
@ratatatCat Apologies for a late review, I forgot about this.

I thought your implementation of random ordering and tests made a great start. There may be room for improvement with regards to how to order randomly, but let's save that room for another issue and PR.

Thanks very much for working on this issue. Congratulations on making your 1st contribution to `whats-new-in-emberland`! 🧡

**Comment by ratatatCat** [comment]
Sounds good! And thank you so much for your help and feedback, @ijlee2!
